### ISSUE TITLE
Android App无法从assets资源中加载jpg图片

### ISSUE THREAD

**Issue by litlight** [zlgopen/awtk-android#2]
使用awtk-demos.v2版本中的新风系统在Android下运行，发现背景图片不显示
经过测试，发现可以加载assets目录下的png图片，但是不能加载assets目录下的jpg图片。
原因是try_load_image时，对于JPG图片类型，会判断图片是否存在，如果不存在，则会将图片名称的jpg后缀修改为jpeg。如果不执行下面的代码，则可以正常加载jpg图片。
assets_manager.c中的try_load_image函数
if (subtype == ASSET_TYPE_IMAGE_JPG && !file_exist(path)) {
    uint32_t len = strlen(path);
    return_value_if_fail(MAX_PATH > len, NULL);
    memcpy(path + len - 4, ".jpeg", 5);
    path[len + 1] = '\0';
  }

判断文件是否存在的file_exist函数在Android下运行好像有些问题，因为对于文件路径assets/default/raw/image/xx/bg0_mix.jpg是否存在的判断，会始终返回false。
具体的判断，调用的应该是ndk的stat，但是这个stat的返回结果可能和预期不符。
fs_os.c中的fs_os_stat函数
struct stat st;
stat_ret = stat(name, &st);
if (stat_ret == -1) {
  return RET_FAIL;
} else {
  return fs_stat_info_from_stat(fst, &st);
}

**Comment by WNsACE** [comment]
这个问题的具体问题已经找到了，现在正在修复中

**Comment by litlight** [comment]
可能是 file_exist 方法可以无法判断相对路径 assets/default/raw/image/xx/xxx.jpg 是否存在，始终会返回false。

**Comment by xianjimli** [comment]
改了，你更新代码试试。谢谢。

**Comment by litlight** [comment]
可以了，图片显示功能已经正常。
